### PR TITLE
add new workflows and new tours

### PR DESCRIPTION
**Pull request by bgruening**
All new tours and workflows needs to be added to the Container as well.
ping @eteriSokhoyan

### CODE REVIEW

**Comment by eteriSokhoyan** [comment]
Pinged) 
What you mean? What should i do?

**Comment by bgruening** [comment]
Nothing, just look at the PR. This will add everything to the container. This is just for your information :)

**Comment by eteriSokhoyan** [comment]
Ah ok) thnx))

**Comment by bgruening** [comment]
@eteriSokhoyan @mmiladi in one hour the new container has new workflows and the new tours.

**Comment by mmiladi** [comment]
Thanks  @bgruening!

**Pull request merged**
