### PR TITLE
use the a new Galaxy version

### PR DESCRIPTION
**Pull request by bgruening**
ping @mmiladi

### CODE REVIEW

**Comment by mmiladi** [comment]
Thanks @bgruening . The docker container for this branch is under construction now!

**Comment by bgruening** [comment]
Under construction? :)

**Comment by mmiladi** [comment]
Under building :) finished now and the small test passed. Yet we should wait for more testing before merge ;)

**Comment by bgruening** [comment]
ping @mmiladi

**Comment by mmiladi** [comment]
Let's upgrade? Is it ready to merge? @bgruening

**Comment by mmiladi** [comment]
ping @bgruening :)

**Comment by bgruening** [comment]
Travis is passing, this is what I can tell :)
Either we it is working or we need to improve our testing!

If we merge it would be nice if you can spend some time and test it as the paper will be out soon, right ;)
So up to you ;)

**Comment by mmiladi** [comment]
@bgruening genau! Soon very soon ;)

**Pull request merged**
