### PR TITLE
add personalized startup page

### PR DESCRIPTION
**Pull request by bgruening**
Start for: https://github.com/BackofenLab/docker-galaxy-graphclust/issues/4

The Image could be modified and more text could be added. Hopefully the link to the tour will work and I added de.NBI and Uni-Freiburg founding.

### CODE REVIEW

**Comment by mmiladi** [comment]
Thanks much Bjoern

**Comment by mmiladi** [comment]
@bgruening I am looking into it to see what could be changed

**Comment by bgruening** [comment]
We can merge these changes and skip the tests if you like.

**Comment by mmiladi** [comment]
Agree, I merge it to have a new docker build triggered

**Pull request merged**
